//! Zone-geometry resolution for zone-only alerts.
//!
//! Many NWS products (most watches and advisories, special weather statements,
//! marine and fire-weather alerts) are issued against UGC *zones* rather than a
//! drawn polygon, so the active-alerts feed returns them with null geometry. The
//! API has no bulk-geometry endpoint — resolving each referenced zone over the
//! network would mean ~1k requests for a typical national alert set.
//!
//! Instead the zone polygons are baked into the binary: a simplified geometry
//! table generated by `tools/build_zone_geometry.py` from the official NWS
//! shapefiles. Resolution is then a pure local lookup, no network involved.

use std::collections::HashMap;

use super::types::{Alert, AlertGeometry};

/// Simplified NWS zone polygons, generated by `tools/build_zone_geometry.py`.
/// A JSON map of "<type>/<id>" (matching the tail of an alert's affectedZones
/// URL, e.g. "forecast/ALZ019") to a list of polygons, each a list of rings,
/// each ring a list of `[lon, lat]` pairs. ~1.2 MB gzipped over the wire.
static ZONE_GEOMETRY_JSON: &[u8] = include_bytes!("../../assets/zone_geometry.json");

/// On-disk shape of [`ZONE_GEOMETRY_JSON`]: zone key -> polygons -> rings -> pts.
type RawZones = HashMap<String, Vec<Vec<Vec<(f64, f64)>>>>;

/// Resolves footprints for zone-only alerts from the baked geometry table.
/// The table is parsed lazily on first use so it costs nothing until an alert
/// actually needs it.
#[derive(Default)]
pub struct ZoneResolver {
    zones: HashMap<String, AlertGeometry>,
    loaded: bool,
}

impl ZoneResolver {
    pub fn new() -> Self {
        Self::default()
    }

    /// Fill in geometry for any zone-only alert by stitching together its
    /// referenced zones' polygons. Returns true if any alert's geometry changed.
    pub fn resolve(&mut self, alerts: &mut [Alert]) -> bool {
        // Nothing to do (and no reason to pay the one-time parse) unless some
        // alert is still missing a footprint but lists zones to resolve from.
        let needs = alerts
            .iter()
            .any(|a| a.geometry.is_empty() && !a.affected_zones.is_empty());
        if !needs {
            return false;
        }
        self.ensure_loaded();

        let mut changed = false;
        for alert in alerts.iter_mut() {
            if !alert.geometry.is_empty() || alert.affected_zones.is_empty() {
                continue;
            }
            let mut merged = AlertGeometry::default();
            for url in &alert.affected_zones {
                if let Some(geom) = zone_key(url).and_then(|k| self.zones.get(k)) {
                    merged.polygons.extend(geom.polygons.iter().cloned());
                }
            }
            if !merged.polygons.is_empty() {
                merged.recompute_bbox();
                alert.geometry = merged;
                changed = true;
            }
        }
        changed
    }

    /// Parse the baked geometry table into the lookup map, once.
    fn ensure_loaded(&mut self) {
        if self.loaded {
            return;
        }
        self.loaded = true;
        match serde_json::from_slice::<RawZones>(ZONE_GEOMETRY_JSON) {
            Ok(raw) => {
                self.zones = raw
                    .into_iter()
                    .map(|(key, polygons)| {
                        let mut geom = AlertGeometry {
                            polygons,
                            bbox: None,
                        };
                        geom.recompute_bbox();
                        (key, geom)
                    })
                    .collect();
                log::info!("loaded {} alert zone geometries", self.zones.len());
            }
            Err(e) => log::error!("failed to parse bundled zone geometry: {}", e),
        }
    }
}

/// Extract the "<type>/<id>" lookup key from an affectedZones URL such as
/// `https://api.weather.gov/zones/forecast/ALZ019`.
fn zone_key(url: &str) -> Option<&str> {
    url.split("/zones/").nth(1)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::alerts::AlertSeverity;
    use wasm_bindgen_test::wasm_bindgen_test;

    fn zone_only_alert(zones: &[&str]) -> Alert {
        Alert {
            id: "test".into(),
            event: "Flood Watch".into(),
            headline: String::new(),
            description: String::new(),
            instruction: String::new(),
            severity: AlertSeverity::Moderate,
            urgency: String::new(),
            certainty: String::new(),
            area_desc: String::new(),
            sender: String::new(),
            effective_secs: None,
            onset_secs: None,
            expires_secs: None,
            ends_secs: None,
            geometry: AlertGeometry::default(),
            affected_zones: zones.iter().map(|z| z.to_string()).collect(),
        }
    }

    #[wasm_bindgen_test]
    fn zone_key_extracts_type_and_id() {
        assert_eq!(
            zone_key("https://api.weather.gov/zones/forecast/ALZ019"),
            Some("forecast/ALZ019")
        );
        assert_eq!(zone_key("not-a-zone-url"), None);
    }

    #[wasm_bindgen_test]
    fn resolve_fills_geometry_from_baked_table() {
        // ALZ019 (Calhoun, AL) is a known forecast zone in the baked table.
        let mut alerts = vec![zone_only_alert(&[
            "https://api.weather.gov/zones/forecast/ALZ019",
        ])];
        let mut resolver = ZoneResolver::new();
        assert!(resolver.resolve(&mut alerts));
        assert!(!alerts[0].geometry.is_empty());
        assert!(alerts[0].geometry.bbox.is_some());
    }

    #[wasm_bindgen_test]
    fn resolve_noop_without_zone_only_alerts() {
        let mut resolver = ZoneResolver::new();
        // An alert that already has geometry (no zones) needs no resolution.
        let mut already = zone_only_alert(&[]);
        already.geometry.polygons.push(vec![vec![(0.0, 0.0); 4]]);
        already.geometry.recompute_bbox();
        let mut alerts = vec![already];
        assert!(!resolver.resolve(&mut alerts));
    }

    #[wasm_bindgen_test]
    fn resolve_leaves_unknown_zone_unresolved() {
        let mut alerts = vec![zone_only_alert(&[
            "https://api.weather.gov/zones/forecast/ZZZ999",
        ])];
        let mut resolver = ZoneResolver::new();
        assert!(!resolver.resolve(&mut alerts));
        assert!(alerts[0].geometry.is_empty());
    }
}
