//! Zone-geometry resolution for zone-only alerts.
//!
//! Many NWS products (most watches and advisories, special weather statements,
//! marine and fire-weather alerts) are issued against UGC *zones* rather than a
//! drawn polygon, so the active-alerts feed returns them with null geometry. The
//! API has no bulk-geometry endpoint — resolving each referenced zone over the
//! network would mean ~1k requests for a typical national alert set.
//!
//! Instead the zone polygons are baked into the binary: a simplified geometry
//! table generated by `tools/build_zone_geometry.py` from the official NWS
//! shapefiles. Resolution is then a pure local lookup, no network involved.

use std::collections::HashMap;

use i_overlay::core::fill_rule::FillRule;
use i_overlay::core::overlay_rule::OverlayRule;
use i_overlay::float::single::SingleFloatOverlay;

use super::types::{triangulate_polygons, Alert, AlertGeometry, Ring};

/// Drop merged rings thinner than this effective width (degrees, `2·area/
/// perimeter`). The gap "slivers" left where independently-simplified adjacent
/// zone borders don't quite meet are long and thin (width ≲ the bake's 0.02°
/// simplification tolerance); real excluded-area holes (lakes, omitted counties)
/// are chunky and far wider. Thinness, not area, separates them.
const MIN_RING_WIDTH: f64 = 0.05;

/// Simplified NWS zone polygons, generated by `tools/build_zone_geometry.py`.
/// A JSON map of "<type>/<id>" (matching the tail of an alert's affectedZones
/// URL, e.g. "forecast/ALZ019") to a list of polygons, each a list of rings,
/// each ring a list of `[lon, lat]` pairs. ~1.2 MB gzipped over the wire.
static ZONE_GEOMETRY_JSON: &[u8] = include_bytes!("../../assets/zone_geometry.json");

/// On-disk shape of [`ZONE_GEOMETRY_JSON`]: zone key -> polygons -> rings -> pts.
type RawZones = HashMap<String, Vec<Vec<Vec<(f64, f64)>>>>;

/// Resolves footprints for zone-only alerts from the baked geometry table.
/// The table is parsed lazily on first use so it costs nothing until an alert
/// actually needs it.
#[derive(Default)]
pub struct ZoneResolver {
    zones: HashMap<String, AlertGeometry>,
    loaded: bool,
}

impl ZoneResolver {
    pub fn new() -> Self {
        Self::default()
    }

    /// Fill in geometry for any zone-only alert by stitching together its
    /// referenced zones' polygons. Returns true if any alert's geometry changed.
    pub fn resolve(&mut self, alerts: &mut [Alert]) -> bool {
        // Nothing to do (and no reason to pay the one-time parse) unless some
        // alert is still missing a footprint but lists zones to resolve from.
        let needs = alerts
            .iter()
            .any(|a| a.geometry.is_empty() && !a.affected_zones.is_empty());
        if !needs {
            return false;
        }
        self.ensure_loaded();

        let mut changed = false;
        for alert in alerts.iter_mut() {
            if !alert.geometry.is_empty() || alert.affected_zones.is_empty() {
                continue;
            }
            let mut merged = AlertGeometry::default();
            for url in &alert.affected_zones {
                if let Some(geom) = zone_key(url).and_then(|k| self.zones.get(k)) {
                    merged.polygons.extend(geom.polygons.iter().cloned());
                }
            }
            if !merged.polygons.is_empty() {
                // Dissolve the many adjacent zone polygons into the alert's outer
                // perimeter(s) so a watch over dozens of counties draws one clean
                // outline instead of dozens with noisy internal borders.
                merged.polygons = dissolve_polygons(merged.polygons);
                merged.recompute_bbox();
                alert.fill_triangles = triangulate_polygons(&merged.polygons);
                alert.geometry = merged;
                changed = true;
            }
        }
        changed
    }

    /// Parse the baked geometry table into the lookup map, once.
    fn ensure_loaded(&mut self) {
        if self.loaded {
            return;
        }
        self.loaded = true;
        match serde_json::from_slice::<RawZones>(ZONE_GEOMETRY_JSON) {
            Ok(raw) => {
                self.zones = raw
                    .into_iter()
                    .map(|(key, polygons)| {
                        let mut geom = AlertGeometry {
                            polygons,
                            bbox: None,
                        };
                        geom.recompute_bbox();
                        (key, geom)
                    })
                    .collect();
                log::info!("loaded {} alert zone geometries", self.zones.len());
            }
            Err(e) => log::error!("failed to parse bundled zone geometry: {}", e),
        }
    }
}

/// Extract the "<type>/<id>" lookup key from an affectedZones URL such as
/// `https://api.weather.gov/zones/forecast/ALZ019`.
fn zone_key(url: &str) -> Option<&str> {
    url.split("/zones/").nth(1)
}

/// Dissolve a set of polygons (in our `[outer, hole, …]` ring form) into the
/// union of their areas, removing the shared internal borders so a watch over
/// many zones draws one clean outline and fills as one region.
///
/// Uses i_overlay's self-union with the **NonZero** fill rule (overlaps stay
/// filled rather than being XOR-ed out), then drops the thin sliver rings left
/// where independently-simplified adjacent zone borders don't quite meet (see
/// [`is_sliver`]). Returns the input unchanged if the union comes back empty.
fn dissolve_polygons(polygons: Vec<Vec<Ring>>) -> Vec<Vec<Ring>> {
    if polygons.len() < 2 {
        return polygons;
    }
    // Feed every ring as a flat list of open contours. i_overlay arranges them
    // together; with the NonZero fill rule, same-wound exteriors union and
    // oppositely-wound holes subtract. The baked data is *not* consistently
    // wound (a handful of zones have CCW exteriors), which would cancel under
    // NonZero and split contiguous regions — so force exteriors clockwise and
    // holes counter-clockwise here.
    let mut contours: Vec<Vec<[f64; 2]>> = Vec::new();
    for rings in &polygons {
        for (i, ring) in rings.iter().enumerate() {
            contours.push(oriented_open_contour(ring, /* clockwise = */ i == 0));
        }
    }

    // Union all contours (NonZero) against an empty clip — dissolves shared
    // borders and merges overlaps.
    let empty: Vec<Vec<[f64; 2]>> = Vec::new();
    let merged = contours.overlay(&empty, OverlayRule::Union, FillRule::NonZero);
    if merged.is_empty() {
        return polygons;
    }

    // Shapes -> our `[exterior, hole, …]` form, re-closing each ring and
    // dropping thin sliver rings (the gap artifacts between simplified zones).
    // If a shape's exterior is itself a sliver, drop the whole shape.
    let mut out = Vec::with_capacity(merged.len());
    for shape in merged {
        let mut rings: Vec<Ring> = Vec::with_capacity(shape.len());
        for (i, contour) in shape.into_iter().enumerate() {
            if is_sliver(&contour) {
                if i == 0 {
                    rings.clear();
                    break; // exterior is a sliver — drop the whole shape
                }
                continue; // interior sliver — drop just this hole
            }
            rings.push(closed_ring(contour));
        }
        if !rings.is_empty() {
            out.push(rings);
        }
    }
    if out.is_empty() {
        polygons
    } else {
        out
    }
}

/// True if a contour is a thin sliver — effective width (`2·area/perimeter`)
/// below [`MIN_RING_WIDTH`].
fn is_sliver(contour: &[[f64; 2]]) -> bool {
    let n = contour.len();
    if n < 3 {
        return true;
    }
    let mut area2 = 0.0;
    let mut perim = 0.0;
    for i in 0..n {
        let a = contour[i];
        let b = contour[(i + 1) % n];
        area2 += a[0] * b[1] - b[0] * a[1];
        perim += ((b[0] - a[0]).powi(2) + (b[1] - a[1]).powi(2)).sqrt();
    }
    let area = (area2 * 0.5).abs();
    perim <= 0.0 || 2.0 * area / perim < MIN_RING_WIDTH
}

/// Our closed ring → an i_overlay open contour, reoriented to the requested
/// winding (clockwise when `clockwise`, else counter-clockwise).
fn oriented_open_contour(ring: &Ring, clockwise: bool) -> Vec<[f64; 2]> {
    let mut c: Vec<[f64; 2]> = ring.iter().map(|&(x, y)| [x, y]).collect();
    if c.len() > 1 && c.first() == c.last() {
        c.pop();
    }
    // Shoelace sign: negative = clockwise in (lon, lat) space.
    let mut area2 = 0.0;
    for i in 0..c.len() {
        let a = c[i];
        let b = c[(i + 1) % c.len()];
        area2 += a[0] * b[1] - b[0] * a[1];
    }
    let is_cw = area2 < 0.0;
    if is_cw != clockwise {
        c.reverse();
    }
    c
}

/// An i_overlay open contour → our closed ring (first == last).
fn closed_ring(contour: Vec<[f64; 2]>) -> Ring {
    let mut ring: Ring = contour.into_iter().map(|p| (p[0], p[1])).collect();
    if let Some(&first) = ring.first() {
        if ring.last() != Some(&first) {
            ring.push(first);
        }
    }
    ring
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::alerts::AlertSeverity;
    use wasm_bindgen_test::wasm_bindgen_test;

    fn zone_only_alert(zones: &[&str]) -> Alert {
        Alert {
            id: "test".into(),
            event: "Flood Watch".into(),
            headline: String::new(),
            description: String::new(),
            instruction: String::new(),
            severity: AlertSeverity::Moderate,
            urgency: String::new(),
            certainty: String::new(),
            area_desc: String::new(),
            sender: String::new(),
            effective_secs: None,
            onset_secs: None,
            expires_secs: None,
            ends_secs: None,
            geometry: AlertGeometry::default(),
            affected_zones: zones.iter().map(|z| z.to_string()).collect(),
            fill_triangles: Vec::new(),
        }
    }

    #[wasm_bindgen_test]
    fn no_baked_zone_spans_the_antimeridian() {
        // An antimeridian-spanning zone (lon range > 180°) has a globe-sized
        // bbox, so it would register as "in view" everywhere and render as lines
        // across the whole map. The generator drops these; guard against them
        // creeping back in on a regen.
        let raw: RawZones = serde_json::from_slice(ZONE_GEOMETRY_JSON).unwrap();
        for (key, polys) in &raw {
            let xs: Vec<f64> = polys.iter().flatten().flatten().map(|&(x, _)| x).collect();
            let span = xs.iter().cloned().fold(f64::MIN, f64::max)
                - xs.iter().cloned().fold(f64::MAX, f64::min);
            assert!(
                span <= 180.0,
                "zone {} spans {:.0}° of longitude",
                key,
                span
            );
        }
    }

    #[wasm_bindgen_test]
    fn zone_key_extracts_type_and_id() {
        assert_eq!(
            zone_key("https://api.weather.gov/zones/forecast/ALZ019"),
            Some("forecast/ALZ019")
        );
        assert_eq!(zone_key("not-a-zone-url"), None);
    }

    #[wasm_bindgen_test]
    fn resolve_fills_geometry_from_baked_table() {
        // ALZ019 (Calhoun, AL) is a known forecast zone in the baked table.
        let mut alerts = vec![zone_only_alert(&[
            "https://api.weather.gov/zones/forecast/ALZ019",
        ])];
        let mut resolver = ZoneResolver::new();
        assert!(resolver.resolve(&mut alerts));
        assert!(!alerts[0].geometry.is_empty());
        assert!(alerts[0].geometry.bbox.is_some());
    }

    #[wasm_bindgen_test]
    fn resolve_noop_without_zone_only_alerts() {
        let mut resolver = ZoneResolver::new();
        // An alert that already has geometry (no zones) needs no resolution.
        let mut already = zone_only_alert(&[]);
        already.geometry.polygons.push(vec![vec![(0.0, 0.0); 4]]);
        already.geometry.recompute_bbox();
        let mut alerts = vec![already];
        assert!(!resolver.resolve(&mut alerts));
    }

    #[wasm_bindgen_test]
    fn dissolve_real_zones_drops_slivers_keeps_real_holes() {
        let raw: RawZones = serde_json::from_slice(ZONE_GEOMETRY_JSON).unwrap();
        let collect = |prefix: &str| -> Vec<Vec<Ring>> {
            let mut v = Vec::new();
            for (k, polys) in &raw {
                if k.starts_with(prefix) {
                    v.extend(polys.clone());
                }
            }
            v
        };
        // Colorado's forecast zones tile it completely, so the dissolve must
        // collapse to a single ring with no internal sliver-hole borders.
        let co = dissolve_polygons(collect("forecast/CO"));
        let co_rings: usize = co.iter().map(|p| p.len()).sum();
        assert_eq!(co.len(), 1, "Colorado should merge to one polygon");
        assert_eq!(co_rings, 1, "Colorado should have no interior sliver holes");

        // Florida contains Lake Okeechobee — a real, chunky hole that must
        // survive the sliver filter.
        let fl = dissolve_polygons(collect("forecast/FL"));
        let fl_holes: usize = fl.iter().map(|p| p.len().saturating_sub(1)).sum();
        assert!(fl_holes >= 1, "Florida should keep its real lake hole");
    }

    #[wasm_bindgen_test]
    fn dissolve_merges_overlapping_squares() {
        // Independently-simplified adjacent zones overlap along their shared
        // border; the dissolve must merge them into one polygon with no internal
        // edge (a single exterior ring, no holes). Rings are clockwise, matching
        // the baked zone winding.
        let left: Ring = vec![(0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)];
        let right: Ring = vec![(0.6, 0.0), (0.6, 1.0), (1.6, 1.0), (1.6, 0.0), (0.6, 0.0)];
        let out = dissolve_polygons(vec![vec![left], vec![right]]);
        assert_eq!(out.len(), 1, "overlapping squares should merge into one");
        assert_eq!(
            out[0].len(),
            1,
            "merged result should have no interior ring"
        );

        let xs: Vec<f64> = out[0][0].iter().map(|&(x, _)| x).collect();
        let max_x = xs.iter().cloned().fold(f64::MIN, f64::max);
        let min_x = xs.iter().cloned().fold(f64::MAX, f64::min);
        assert!((min_x - 0.0).abs() < 1e-6 && (max_x - 1.6).abs() < 1e-6);
    }

    #[wasm_bindgen_test]
    fn dissolve_keeps_far_apart_polygons_separate() {
        // Two disjoint squares 50° apart must not be joined by a connecting
        // edge (that would be a map-spanning spike). Either kept separate by the
        // union, or the edge guard falls back to the originals — both fine, and
        // crucially no long edge survives.
        let near: Ring = vec![(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0), (0.0, 0.0)];
        let far: Ring = vec![
            (50.0, 0.0),
            (51.0, 0.0),
            (51.0, 1.0),
            (50.0, 1.0),
            (50.0, 0.0),
        ];
        let out = dissolve_polygons(vec![vec![near], vec![far]]);
        assert_eq!(out.len(), 2, "disjoint polygons must stay separate");
        // No coordinate should stray outside the inputs' combined bounds.
        for &(x, y) in out.iter().flatten().flatten() {
            assert!((-1.0..=52.0).contains(&x) && (-1.0..=2.0).contains(&y));
        }
    }

    #[wasm_bindgen_test]
    fn triangulate_covers_area_and_excludes_holes() {
        // 4×4 square with a 2×2 centered hole → fill area ≈ 12, and the hole
        // center must lie in no triangle.
        let outer: Ring = vec![(0.0, 0.0), (4.0, 0.0), (4.0, 4.0), (0.0, 4.0), (0.0, 0.0)];
        let hole: Ring = vec![(1.0, 1.0), (1.0, 3.0), (3.0, 3.0), (3.0, 1.0), (1.0, 1.0)];
        let tris = triangulate_polygons(&[vec![outer, hole]]);
        assert!(!tris.is_empty());
        let area: f64 = tris
            .iter()
            .map(|t| {
                ((t[1].0 - t[0].0) * (t[2].1 - t[0].1) - (t[2].0 - t[0].0) * (t[1].1 - t[0].1))
                    .abs()
                    / 2.0
            })
            .sum();
        assert!((area - 12.0).abs() < 0.01, "fill area was {}", area);

        let in_tri = |p: (f64, f64), t: &[(f64, f64); 3]| {
            let sign = |a: (f64, f64), b: (f64, f64), c: (f64, f64)| {
                (a.0 - c.0) * (b.1 - c.1) - (b.0 - c.0) * (a.1 - c.1)
            };
            let (d1, d2, d3) = (
                sign(p, t[0], t[1]),
                sign(p, t[1], t[2]),
                sign(p, t[2], t[0]),
            );
            !((d1 < 0.0 || d2 < 0.0 || d3 < 0.0) && (d1 > 0.0 || d2 > 0.0 || d3 > 0.0))
        };
        assert!(
            !tris.iter().any(|t| in_tri((2.0, 2.0), t)),
            "hole center should be uncovered by the fill"
        );
    }

    #[wasm_bindgen_test]
    fn dissolve_single_polygon_is_unchanged() {
        let square: Ring = vec![(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0), (0.0, 0.0)];
        let polys = vec![vec![square]];
        assert_eq!(dissolve_polygons(polys.clone()), polys);
    }

    #[wasm_bindgen_test]
    fn resolve_leaves_unknown_zone_unresolved() {
        let mut alerts = vec![zone_only_alert(&[
            "https://api.weather.gov/zones/forecast/ZZZ999",
        ])];
        let mut resolver = ZoneResolver::new();
        assert!(!resolver.resolve(&mut alerts));
        assert!(alerts[0].geometry.is_empty());
    }
}
