//! Web Worker-based decode offloading.
//!
//! Moves the expensive `nexrad::load()` call (bzip2 decompression + protocol decode,
//! 500-3000ms) off the main UI thread into a dedicated Web Worker. Communication uses
//! `postMessage` with Transferable ArrayBuffers for zero-copy data transfer.
//!
//! The worker loads the same WASM binary as the main thread. The `start()` function
//! detects the worker context (no `window`) and exits early, leaving only the
//! `worker_decode` export available to the worker JS shim.

use ::nexrad::model::data::Scan;
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{MessageEvent, Worker, WorkerOptions, WorkerType};

/// Unique ID for tracking decode requests.
type RequestId = u64;

/// Context describing what triggered a decode request, so the result handler
/// in the main update loop knows which state updates to apply.
pub enum DecodeContext {
    /// Decode triggered by archive download completion.
    Download {
        timestamp: i64,
        #[allow(dead_code)]
        file_name: String,
        #[allow(dead_code)]
        is_cache_hit: bool,
        fetch_latency_ms: f64,
    },
    /// Decode triggered by scrubbing to a cached scan.
    Scrub { timestamp: i64 },
    /// Decode triggered by realtime volume completion.
    Realtime { timestamp: i64 },
    /// Decode triggered by partial volume assembly (incremental realtime).
    PartialDecode { timestamp_ms: i64 },
}

/// Successful decode result from the worker.
pub struct DecodeResult {
    /// The context that triggered this decode.
    pub context: DecodeContext,
    /// The decoded radar volume.
    pub scan: Scan,
    /// Time spent in the worker (decode + serialize), in milliseconds.
    pub worker_decode_ms: f64,
    /// Time spent deserializing on the main thread, in milliseconds.
    #[allow(dead_code)]
    pub deserialize_ms: f64,
}

/// Failed decode result from the worker.
pub struct DecodeErrorResult {
    /// The context that triggered this decode.
    pub context: DecodeContext,
    /// Error message from the worker.
    pub message: String,
}

/// Outcome of a worker decode operation.
pub enum DecodeOutcome {
    Success(DecodeResult),
    Error(DecodeErrorResult),
}

/// Manages a dedicated Web Worker for NEXRAD decode operations.
///
/// Created once at app startup and kept alive for the entire session.
/// Requests are submitted via `decode()` and results polled via `try_recv()`
/// each frame, following the same pattern as other channels in the app.
pub struct DecodeWorker {
    worker: Worker,
    next_id: u64,
    ready: Rc<RefCell<bool>>,
    pending: Rc<RefCell<HashMap<RequestId, DecodeContext>>>,
    results: Rc<RefCell<Vec<DecodeOutcome>>>,
    /// Requests queued before the worker was ready.
    queue: Vec<(RequestId, Vec<u8>)>,
}

impl DecodeWorker {
    /// Create a new decode worker.
    ///
    /// Discovers the WASM/JS URLs from the current page's `<link>` tags
    /// (generated by Trunk), creates a module worker, and sends the init message.
    /// The worker will post a "ready" message once WASM is initialized.
    pub fn new(ctx: eframe::egui::Context) -> Result<Self, String> {
        let js_url =
            discover_js_url().ok_or_else(|| "Could not find JS module URL in DOM".to_string())?;
        let wasm_url =
            discover_wasm_url().ok_or_else(|| "Could not find WASM URL in DOM".to_string())?;

        log::info!(
            "Creating decode worker with JS={}, WASM={}",
            js_url,
            wasm_url
        );

        // Create an ES module worker
        let mut opts = WorkerOptions::new();
        #[allow(deprecated)]
        opts.type_(WorkerType::Module);

        let worker = Worker::new_with_options("worker.js", &opts)
            .map_err(|e| format!("Failed to create Worker: {:?}", e))?;

        let ready = Rc::new(RefCell::new(false));
        let pending: Rc<RefCell<HashMap<RequestId, DecodeContext>>> =
            Rc::new(RefCell::new(HashMap::new()));
        let results: Rc<RefCell<Vec<DecodeOutcome>>> = Rc::new(RefCell::new(Vec::new()));

        // Set up the onmessage handler
        {
            let ready_c = ready.clone();
            let pending_c = pending.clone();
            let results_c = results.clone();
            let ctx_c = ctx.clone();

            let onmessage = Closure::<dyn Fn(MessageEvent)>::new(move |event: MessageEvent| {
                let data = event.data();
                let msg_type = js_sys::Reflect::get(&data, &"type".into())
                    .ok()
                    .and_then(|v| v.as_string());

                match msg_type.as_deref() {
                    Some("ready") => {
                        *ready_c.borrow_mut() = true;
                        log::info!("Decode worker ready");
                    }
                    Some("decoded") => {
                        handle_decoded_message(&data, &pending_c, &results_c);
                        ctx_c.request_repaint();
                    }
                    Some("error") => {
                        handle_error_message(&data, &pending_c, &results_c);
                        ctx_c.request_repaint();
                    }
                    other => {
                        log::warn!("Unknown worker message type: {:?}", other);
                    }
                }
            });

            worker.set_onmessage(Some(onmessage.as_ref().unchecked_ref()));
            onmessage.forget(); // Lives for app lifetime
        }

        // Set up onerror handler
        {
            let onerror = Closure::<dyn Fn(web_sys::ErrorEvent)>::new(
                move |event: web_sys::ErrorEvent| {
                    log::error!(
                        "Decode worker error: {} ({}:{})",
                        event.message(),
                        event.filename(),
                        event.lineno()
                    );
                },
            );

            worker.set_onerror(Some(onerror.as_ref().unchecked_ref()));
            onerror.forget();
        }

        // Send init message with the WASM/JS URLs
        let init_msg = js_sys::Object::new();
        js_sys::Reflect::set(&init_msg, &"type".into(), &"init".into()).ok();
        js_sys::Reflect::set(&init_msg, &"jsUrl".into(), &js_url.into()).ok();
        js_sys::Reflect::set(&init_msg, &"wasmUrl".into(), &wasm_url.into()).ok();

        worker
            .post_message(&init_msg)
            .map_err(|e| format!("Failed to send init message: {:?}", e))?;

        Ok(Self {
            worker,
            next_id: 1,
            ready,
            pending,
            results,
            queue: Vec::new(),
        })
    }

    /// Submit raw NEXRAD archive bytes for decoding in the worker.
    ///
    /// The data is transferred (zero-copy) to the worker. If the worker is not
    /// yet ready, the request is queued and flushed automatically.
    pub fn decode(&mut self, data: Vec<u8>, context: DecodeContext) {
        let id = self.next_id;
        self.next_id += 1;

        self.pending.borrow_mut().insert(id, context);

        if *self.ready.borrow() {
            send_decode_request(&self.worker, id, &data);
        } else {
            log::debug!("Worker not ready, queuing decode request {}", id);
            self.queue.push((id, data));
        }
    }

    /// Flush any queued requests if the worker has become ready.
    /// Call this each frame before polling results.
    pub fn flush_queue(&mut self) {
        if *self.ready.borrow() && !self.queue.is_empty() {
            let queued: Vec<_> = self.queue.drain(..).collect();
            log::info!("Flushing {} queued decode requests", queued.len());
            for (id, data) in queued {
                send_decode_request(&self.worker, id, &data);
            }
        }
    }

    /// Poll for completed decode results. Call this each frame in the update loop.
    pub fn try_recv(&mut self) -> Vec<DecodeOutcome> {
        self.flush_queue();
        self.results.borrow_mut().drain(..).collect()
    }

    /// Returns true if the worker has initialized and is ready to accept requests.
    #[allow(dead_code)]
    pub fn is_ready(&self) -> bool {
        *self.ready.borrow()
    }
}

/// Handle a "decoded" message from the worker.
fn handle_decoded_message(
    data: &JsValue,
    pending: &Rc<RefCell<HashMap<RequestId, DecodeContext>>>,
    results: &Rc<RefCell<Vec<DecodeOutcome>>>,
) {
    let id = js_sys::Reflect::get(data, &"id".into())
        .ok()
        .and_then(|v| v.as_f64())
        .unwrap_or(0.0) as u64;

    let worker_decode_ms = js_sys::Reflect::get(data, &"decodeMs".into())
        .ok()
        .and_then(|v| v.as_f64())
        .unwrap_or(0.0);

    let context = match pending.borrow_mut().remove(&id) {
        Some(ctx) => ctx,
        None => {
            log::warn!("Received decoded message for unknown request {}", id);
            return;
        }
    };

    // Extract the serialized Scan bytes from the transferred ArrayBuffer
    let scan_buffer = match js_sys::Reflect::get(data, &"data".into()) {
        Ok(val) => val,
        Err(_) => {
            results.borrow_mut().push(DecodeOutcome::Error(DecodeErrorResult {
                context,
                message: "Missing data field in decoded message".to_string(),
            }));
            return;
        }
    };

    let scan_bytes = js_sys::Uint8Array::new(&scan_buffer).to_vec();

    // Deserialize the Scan on the main thread
    let deser_start = web_time::Instant::now();
    match bincode::deserialize::<Scan>(&scan_bytes) {
        Ok(scan) => {
            let deserialize_ms = deser_start.elapsed().as_secs_f64() * 1000.0;
            log::info!(
                "Worker decode: {}ms in worker, {}ms deserialize, {} sweeps",
                worker_decode_ms as u32,
                deserialize_ms as u32,
                scan.sweeps().len()
            );
            results
                .borrow_mut()
                .push(DecodeOutcome::Success(DecodeResult {
                    context,
                    scan,
                    worker_decode_ms,
                    deserialize_ms,
                }));
        }
        Err(e) => {
            log::error!("Failed to deserialize Scan from worker: {}", e);
            results
                .borrow_mut()
                .push(DecodeOutcome::Error(DecodeErrorResult {
                    context,
                    message: format!("Deserialization failed: {}", e),
                }));
        }
    }
}

/// Handle an "error" message from the worker.
fn handle_error_message(
    data: &JsValue,
    pending: &Rc<RefCell<HashMap<RequestId, DecodeContext>>>,
    results: &Rc<RefCell<Vec<DecodeOutcome>>>,
) {
    let id = js_sys::Reflect::get(data, &"id".into())
        .ok()
        .and_then(|v| v.as_f64())
        .unwrap_or(0.0) as u64;

    let message = js_sys::Reflect::get(data, &"message".into())
        .ok()
        .and_then(|v| v.as_string())
        .unwrap_or_else(|| "Unknown worker error".to_string());

    log::error!("Worker decode error (request {}): {}", id, message);

    if let Some(context) = pending.borrow_mut().remove(&id) {
        results
            .borrow_mut()
            .push(DecodeOutcome::Error(DecodeErrorResult { context, message }));
    }
}

/// Send a decode request to the worker, transferring the data buffer.
fn send_decode_request(worker: &Worker, id: u64, data: &[u8]) {
    let array = js_sys::Uint8Array::from(data);
    let buffer = array.buffer();

    let msg = js_sys::Object::new();
    js_sys::Reflect::set(&msg, &"type".into(), &"decode".into()).ok();
    js_sys::Reflect::set(&msg, &"id".into(), &JsValue::from(id as f64)).ok();
    js_sys::Reflect::set(&msg, &"data".into(), &buffer).ok();

    let transfer = js_sys::Array::new();
    transfer.push(&buffer);

    if let Err(e) = worker.post_message_with_transfer(&msg, &transfer) {
        log::error!("Failed to send decode request {}: {:?}", id, e);
    }
}

/// Discover the Trunk-generated JS module URL from DOM `<link rel="modulepreload">` tags.
fn discover_js_url() -> Option<String> {
    let document = web_sys::window()?.document()?;
    let links = document.query_selector_all("link[rel='modulepreload']").ok()?;
    for i in 0..links.length() {
        if let Some(el) = links.get(i) {
            let el: &web_sys::Element = el.unchecked_ref();
            if let Some(href) = el.get_attribute("href") {
                // Find the main app module (not snippet/helper modules)
                if href.contains("nexrad-workbench") && href.ends_with(".js") {
                    return Some(href);
                }
            }
        }
    }
    None
}

/// Discover the Trunk-generated WASM URL from DOM `<link rel="preload">` tags.
fn discover_wasm_url() -> Option<String> {
    let document = web_sys::window()?.document()?;
    let links = document
        .query_selector_all("link[rel='preload'][type='application/wasm']")
        .ok()?;
    if let Some(el) = links.get(0) {
        let el: &web_sys::Element = el.unchecked_ref();
        return el.get_attribute("href");
    }
    None
}
